import './privacy.css';

export default function PrivacyNotice() {
  // let ppl revoke consent from here too
  const handleRevoke = () => {
    localStorage.removeItem('dataConsent');
    localStorage.removeItem('anonUserId');
    window.location.hash = '';
    window.location.reload();
  };

  return (
    <main className="privacy-page fade-in">
      <div className="privacy-container">
        <a href="#" className="privacy-back">Back to app</a>

        <h1>Data collection notice</h1>
        <p className="privacy-updated">Last updated: April 4, 2026</p>

        <section>
          <h2>What this app does</h2>
          <p>
            Math Practice is a free tool for practicing arithmetic. If you
            consent, it tracks your progress anonymously so you can see how
            you're improving.
          </p>
        </section>

        <section>
          <h2>What we collect (with your consent)</h2>
          <p>We only collect data if you explicitly opt in. When you do, we store:</p>
          <ul>
            <li>
              A random anonymous ID generated by your browser and stored
              locally. It is not linked to your name, email, or any account.
            </li>
            <li>
              Practice data: which problems you attempt, whether you got them
              right, and how long each one took.
            </li>
            <li>
              A one-way cryptographic hash of your network address. We never
              store your actual IP. The hash lets us count unique visitors and
              group sessions, but it cannot be reversed to reveal your IP.
            </li>
          </ul>
        </section>

        <section>
          <h2>If you decline consent</h2>
          <p>
            If you choose not to consent, we store nothing at all. No
            anonymous ID, no practice data, no network hash. The app runs
            entirely in your browser with no server communication. You can
            still practice math — you just won't have progress tracking
            across sessions.
          </p>
        </section>

        <section>
          <h2>What we do not collect</h2>
          <ul>
            <li>Your name, email, or any contact info</li>
            <li>Browser fingerprints, advertising IDs, or cookies</li>
            <li>Your location</li>
            <li>Data from other apps or websites</li>
          </ul>
        </section>

        <section>
          <h2>How long we keep data</h2>
          <p>
            Practice attempts are automatically deleted after 90 days. Your
            anonymous user ID persists so returning visitors can continue
            tracking their progress, but it can be deleted on request.
          </p>
        </section>

        <section>
          <h2>Who can access the data</h2>
          <p>
            Only the site administrator, who authenticates with a secret key.
            There is no third-party analytics, no advertising, and no data
            sharing with anyone.
          </p>
        </section>

        <section>
          <h2>Your rights</h2>
          <p>
            Under Quebec's Act respecting the protection of personal
            information in the private sector (Law 25), you have the right to:
          </p>
          <ul>
            <li>Access the data we hold about you</li>
            <li>Request correction of inaccurate data</li>
            <li>Request deletion of your data</li>
            <li>Request portability of your data in a standard format</li>
            <li>Withdraw your consent at any time</li>
            <li>Request de-indexation (right to be forgotten)</li>
          </ul>
          <p>
            To exercise any of these rights, contact us at the address below.
          </p>
        </section>

        <section>
          <h2>How to withdraw consent</h2>
          <p>
            You can withdraw your consent at any time by clicking the button
            below. This will remove your anonymous ID from your browser and
            stop all data collection going forward.
          </p>
          <button className="privacy-revoke-btn" onClick={handleRevoke}>
            Withdraw consent and clear my data
          </button>
          <p className="privacy-small">
            You can also clear your browser's local storage for this site to
            achieve the same result.
          </p>
        </section>

        <section>
          <h2>Contact</h2>
          <p>
            If you have questions about how your data is handled, contact:
          </p>
          <p className="privacy-contact">
            ning.ye@mail.concordia.ca
          </p>
        </section>
      </div>
    </main>
  );
}
